### PR TITLE
Local deploy improvements

### PR DESCRIPTION
**Pull request by henare**
Moved from https://github.com/mlandauer/cuttlefish/pull/271.

The main changes this pull request makes are to add a flag to Capistrano to allow you to deploy to your local test VM without manually editing the Capistrano files. It also doesn't notify Honeybadger on local deploys.

### CODE REVIEW

**Comment by equivalentideas** [comment]
This looks _really_ good @henare 👍 I'm unable to deploy because the version of rvm-capistrano we're using doesn't support rbenv—[same issue we faced over on PlanningAlerts](https://github.com/openaustralia/planningalerts/issues/1104).

I'm going to have a look at that and see if I can fix it as part of these improvements.

**Comment by equivalentideas** [comment]
To get this working I had to, firstly update the rvm-capistrano and capistrano gems (related to support for rbenv which I use) and then `vagrant ssh` `cd /srv/www && sudo rm -r *`. I had to remove all the existing stuff in there because that git repo saw `mlandauer` as `origin`, which meant it was getting confused.

**Comment by equivalentideas** [comment]
I'm getting:

```
  * executing "cd -- /srv/www/releases/20170224050137 && RAILS_ENV=production RAILS_GROUPS=assets bundle exec rake assets:precompile"
    servers: ["localhost"]
    [localhost:2222] executing command
*** [err :: localhost:2222] DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
*** [err :: localhost:2222] Please register a mime type using `register_mime_type` then
*** [err :: localhost:2222] use `register_compressor` or `register_transformer`.
*** [err :: localhost:2222] https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
*** [err :: localhost:2222] (called from block in <class:Railtie> at /srv/www/shared/bundle/ruby/2.1.0/gems/less-rails-2.8.0/lib/less/rails/railtie.rb:16)
*** [err :: localhost:2222]
*** [err :: localhost:2222] rake aborted!
*** [err :: localhost:2222] ActiveRecord::AdapterNotSpecified: 'production' database is not configured. Available: ["development", "test"]
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:248:in `resolve_symbol_connection'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:211:in `resolve_connection'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:139:in `resolve'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/connection_specification.rb:169:in `spec'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/connection_handling.rb:50:in `establish_connection'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railtie.rb:120:in `block (2 levels) in <class:Railtie>'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
*** [err :: localhost:2222] /srv/www/releases/20170224050137/config/environment.rb:5:in `<top (required)>'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/skylight-0.5.2/lib/skylight/probes.rb:81:in `require'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/skylight-0.5.2/lib/skylight/probes.rb:81:in `require'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
*** [err :: localhost:2222] /srv/www/shared/bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
*** [err :: localhost:2222] Tasks: TOP => environment
*** [err :: localhost:2222] (See full trace by running task with --trace)
    command finished in 3377ms
*** [deploy:update_code] rolling back
  * executing "rm -rf /srv/www/releases/20170224050137; true"
    servers: ["localhost"]
    [localhost:2222] executing command
    command finished in 108ms
failed: "rvm_path=/usr/local/lib/rvm /usr/local/lib/rvm/bin/rvm-shell '2.1.5' -c 'cd -- /srv/www/releases/20170224050137 && RAILS_ENV=production RAILS_GROUPS=assets bundle exec rake assets:precompile'" on localhost:2222
```

Investigating ... 🔍 

Aha, the problem here was that by `rm`ing all my `www` directory earlier I had removed the database.yml set in `shared` by our ansible task. Past this now 👍

**Comment by equivalentideas** [comment]
@henare this now works out of the box for me now with these changes. Could you have a look at those last two commits (and the commit messages), and if you're happy merge this?

**Comment by henare** [comment]
Woo, thanks for diving in and making these enhancements @equivalentideas.

**Pull request merged**
